name: Build and publish Container images

on:
  workflow_dispatch:
    inputs:
      build_date:
        description: 'Build date (e.g. 20250515)'
        required: true

env:
  REGISTRY: 'quay.io'
  IMAGE_NAME: 'bitsaver/linguaspark'

jobs:
  base_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_BS_USERNAME }}
          password: ${{ secrets.QUAY_BS_ROBOT_TOKEN }}

      - name: Build and push Container image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: 'linux/amd64'
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.build_date }}
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false

      - name: Sleep
        run: sleep 5

  with_models_image:
    needs: [ 'base_image' ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              symbol: 'combo-a1',
              translation_models: 'enzh'
            }
          - {
              symbol: 'combo-a2',
              translation_models: 'enzh;fren'
            }
          - {
              symbol: 'combo-a3',
              translation_models: 'enzh;deen'
            }
          - {
              symbol: 'combo-a4',
              translation_models: 'enzh;esen'
            }
          - {
              symbol: 'combo-a5',
              translation_models: 'enzh;ruen'
            }
          - {
              symbol: 'combo-a6',
              translation_models: 'enzh;jaen'
            }
          - {
              symbol: 'combo-a7',
              translation_models: 'enzh;koen'
            }
          - {
              symbol: 'combo-b1',
              translation_models: 'enzh;zhen'
            }
          - {
              symbol: 'combo-b2',
              translation_models: 'enzh;jaen;koen;zhen;enja;enko'
            }
          - {
              symbol: 'combo-b3',
              translation_models: 'enzh;zhen;fren;enfr;deen;ende;enes;esen;enru;ruen'
            }
          - {
              symbol: 'combo-b4',
              translation_models: 'enzh;zhen;jaen;enja;koen;enko;fren;enfr;deen;ende;enes;esen'
            }
          - {
              symbol: 'combo-b5',
              translation_models: 'enzh;zhen;jaen;enja;koen;enko;fren;enfr;deen;ende;enes;esen;enru;ruen'
            }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_BS_USERNAME }}
          password: ${{ secrets.QUAY_BS_ROBOT_TOKEN }}

      - name: Download translation models
        shell: bash
        run: |
          mkdir translation-models
          TRANSLATION_MODELS="${{ matrix.config.translation_models }}"
          IFS=';' read -r -a models <<< "$TRANSLATION_MODELS"

          for model in "${models[@]}"; do
            mkdir -p "translation-models/$model"
            if [[ "$model" == "enzh" || "$model" == "enja" ]]; then
              model_set="base"
              files=(
                "lex.50.50.${model}.s2t.bin.gz"
                "model.${model}.intgemm.alphas.bin.gz"
                "srcvocab.${model}.spm.gz"
                "trgvocab.${model}.spm.gz"
              )
            elif [[ "$model" == "jaen" || "$model" == "koen" || "$model" == "zhen" || "$model" == "enko" || "$model" == "enru" ]]; then
              model_set="base"
              files=(
                "lex.50.50.${model}.s2t.bin.gz"
                "model.${model}.intgemm.alphas.bin.gz"
                "vocab.${model}.spm.gz"
              )
            elif [[ "$model" == "fren" || "$model" == "deen" || "$model" == "esen" ]]; then
              model_set="base-memory"
              files=(
                "lex.50.50.${model}.s2t.bin.gz"
                "model.${model}.intgemm.alphas.bin.gz"
                "vocab.${model}.spm.gz"
              )
            elif [[ "$model" == "ruen" || "$model" == "enfr" || "$model" == "ende" ]]; then
              model_set="tiny"
              files=(
                "lex.50.50.${model}.s2t.bin.gz"
                "model.${model}.intgemm.alphas.bin.gz"
                "vocab.${model}.spm.gz"
              )
            elif [[ "$model" == "enes" ]]; then
              model_set="tiny"
              files=(
                "lex.50.50.${model}.s2t.bin.gz"
                "model.${model}.intgemm.alphas.bin.gz"
                "qualityModel.${model}.bin.gz"
                "vocab.${model}.spm.gz"
              )
            else
              files=()
            fi

            base_url="https://github.com/mozilla/firefox-translations-models/raw/refs/heads/main/models/${model_set}/${model}"
            for file in "${files[@]}"; do
              echo "Downloading $file"
              curl -sL "$base_url/$file" -o "translation-models/$model/$file"
              gunzip -f "translation-models/$model/$file"
              extracted_file="${file%.gz}"
              echo "$extracted_file downloaded and extracted"
            done
            echo "Download completed. Model structure:"
            pwd
            ls -R "translation-models/$model"
          done


      - name: Build and push Container image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.models
          platforms: 'linux/amd64'
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-${{ matrix.config.symbol }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.build_date }}-${{ matrix.config.symbol }}
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false

